// <auto-generated />
using System;
using ExpenseService.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ExpenseService.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ExpenseService.Database.Entities.documents", b =>
                {
                    b.Property<int>("DocumentId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("DocumentBytes");

                    b.Property<string>("DocumentName");

                    b.Property<string>("DocumentType");

                    b.Property<int>("ExpenseId");

                    b.Property<int>("UserId");

                    b.HasKey("DocumentId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("ExpenseService.Database.Entities.expense", b =>
                {
                    b.Property<int>("ExpenseId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Comment");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<int>("ExpenseStatus");

                    b.Property<DateTime>("FromDate");

                    b.Property<int>("HotelBills");

                    b.Property<int>("LandlineBills");

                    b.Property<int>("MealsBills");

                    b.Property<int>("Miscellaneous");

                    b.Property<int>("MobileBills");

                    b.Property<int>("ProjectID");

                    b.Property<string>("PurposeorReason");

                    b.Property<DateTime>("ToDate");

                    b.Property<int>("TotalAmount");

                    b.Property<int>("TransportBills");

                    b.Property<int>("TravelBills");

                    b.Property<int>("UserID");

                    b.Property<string>("VoucherID");

                    b.HasKey("ExpenseId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("ExpenseService.Database.Entities.expenseAudit", b =>
                {
                    b.Property<int>("ApprovalExpenseLogId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ApprovalUser");

                    b.Property<string>("Comment");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<int>("ExpenseID");

                    b.Property<DateTime>("ProcessedDate");

                    b.Property<int>("Status");

                    b.Property<int>("UserID");

                    b.HasKey("ApprovalExpenseLogId");

                    b.ToTable("ExpensesAudit");
                });
#pragma warning restore 612, 618
        }
    }
}
